on:
  push:
    branches: [ main ]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:sagitta
      options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'vyos/vyos-build'
          ref: 'current'
      - run: sudo make clean
      - run: sudo ./build-vyos-image generic --architecture amd64 --build-by "m.k@mk16.de" --build-type release --vyos-mirror https://rolling-packages.vyos.net/current/
      - uses: actions/upload-artifact@v4
        with:
          path: build/live-image-amd64.hybrid.iso

